[repository]
name = "hypr-appmenu"
authors = ["memtable", "Alex Hulbert"]
commit_pins = [
    # Hyprland commit                         , hypr-appmenu commit
    ["a0136d8c04687bb36eb8a28eb9d1ff92aea99704", "d7455e4ca57d1d5d5d128cc6d11168ea757ce801"], # v0.55.4
]

[hypr-appmenu]
description = "AppMenu Protocol Plugin for Hyprland"
authors = ["memtable", "Alex Hulbert"]
output = "hypr-appmenu.so"
build = [
    "make all"
]
